# Site settings
title: JordanUrbs.com
email: jordanurbs@pm.me
description: A little about me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Jordan Urbanovich
your-title: Psychonaut and Community Explorer

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/jordanurbs
gitlab_url:
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/jordan-urbanovich-6564b2124/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jordanurbs

# Build settings
markdown: kramdown
